USE [CCBISDW]
GO

/****** Object:  Table [dbo].[DimHandleType]    Script Date: 7/10/2021 3:52:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DimHandleType](
	[HandleType_Key] [int] NOT NULL,
	[HandleType_Desc] [varchar](10) NULL,
 CONSTRAINT [PK__HandleTy__6D7BE7DE64707D74] PRIMARY KEY CLUSTERED 
(
	[HandleType_Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

