USE [CCBISDW]
GO

/****** Object:  Table [dbo].[DimServiceType]    Script Date: 7/10/2021 4:01:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DimServiceType](
	[ServiceType_Key] [int] NOT NULL,
	[ServiceType_Desc] [varchar](50) NULL,
 CONSTRAINT [PK__ServiceT__62FD11060C159455] PRIMARY KEY CLUSTERED 
(
	[ServiceType_Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

